### ISSUE TITLE
Error in Custom SMTP

### ISSUE THREAD

**Issue by AnilChinchawale** [mistio/mist-ee#1]
Hello,

I got an error while adding custom SMTP details in ./settings/settings.py, Please let us know how to fix it.
ERROR: for CL_beat_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for cl_api_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for beat  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for api  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by AnilChinchawale** [comment]
Not able to start docker-compose after making changes in ./settings/settings.py

**Comment by d-mo** [comment]
Hi @AnilChinchawale 

You need to configure a valid SMTP server with a hostname that's addressable from each Mist container. Setting "localhost" won't work because that will resolve to the local ip of the container each service is running in. If you're running an SMTP service on the same machine along with Mist, then you could use the private or public ip address or dns name of that host. Also make sure that the SMTP service is accessible when using that hostname. Please let me know if that helps.

**Comment by AnilChinchawale** [comment]
Hello @d-mo 

Thanks for info , I have stopped containers,added AWS SMTP host,Username,Port and Password and trying to start containers but got reported errors.

**Comment by d-mo** [comment]
What kind of errors? You check the API logs using the command `docker-compose logs api`

**Comment by AnilChinchawale** [comment]
Output after changing setting file :- 

<pre>docker-compose restart
Restarting mist-ee_nginx_1                ... 
Restarting mist-ee_logstash_1             ... 
Restarting mist-ee_celery-gevent_1        ... 
Restarting mist-ee_poller_1               ... 
Restarting mist-ee_celery-prefork_1       ... 
Restarting mist-ee_hubshell_1             ... 
Restarting mist-ee_scheduler_1            ... 
Restarting mist-ee_cilia_1                ... 
Restarting mist-ee_api_1                  ... 
Restarting mist-ee_apply-migrations_1     ... <font color="#4E9A06">done</font>
Restarting mist-ee_beat_1                 ... 
Restarting mist-ee_sockjs_1               ... 
Restarting mist-ee_gocky_1                ... <font color="#4E9A06">done</font>
Restarting mist-ee_elasticsearch-manage_1 ... <font color="#4E9A06">done</font>
Restarting mist-ee_insights-handler_1     ... <font color="#4E9A06">done</font>
Restarting mist-ee_kibana_1               ... 
Restarting mist-ee_ui_1                   ... 
Restarting mist-ee_elements_1             ... 
Restarting mist-ee_elasticsearch_1        ... 
Restarting mist-ee_swagger_1              ... 
Restarting mist-ee_rabbitmq_1             ... 
Restarting mist-ee_traefik_1              ... 
Restarting mist-ee_memcached_1            ... 
Restarting mist-ee_mongodb_1              ... 
Restarting mist-ee_landing_1              ... 
Restarting mist-ee_socat_1                ... 
Restarting mist-ee_mailmock_1             ... 
Restarting mist-ee_influxdb_1             ... 
Restarting mist-ee_manage_1               ... 

ERROR: for mist-ee_sockjs_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_beat_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_celery-gevent_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_logstash_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_elasticsearch_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_scheduler_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_memcached_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_celery-prefork_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_hubshell_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_poller_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_swagger_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_elements_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_ui_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_landing_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_api_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_cilia_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_traefik_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_manage_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_nginx_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_influxdb_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_kibana_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_mongodb_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_mailmock_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_socat_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)

ERROR: for mist-ee_rabbitmq_1  UnixHTTPConnectionPool(host=&apos;localhost&apos;, port=None): Read timed out. (read timeout=70)
<font color="#CC0000">ERROR</font>: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
</pre>

**Comment by d-mo** [comment]
Do you have other services or containers bound on localhost port 80? Maybe a  previous installation of Mist that was not properly shut down? There could be a conflict. Check with `docker ps` and netstat. Also please set CORE_URI in settings/settings.py to the publicly addressable URL of your Mist portal instead of http://localhost which is the default.

**Comment by AnilChinchawale** [comment]
I have verified and checked there no service running on Port 80 also i have checked docker ps and found no container running.
